### ISSUE TITLE
새로고침 시 Localstorage의 AccountObjId와 AccountTitle을 다시 store에 저장하도록 수정

### ISSUE THREAD

**Issue by pkiop** [boostcamp-2020/Project16-A-Account-Book#104]
## 목표
새로고침 하면 store에 저장한 state가 다 날아감
새로고침 시 localStorage에 저장했던 AccountObjId와 AccountTitle을 다시 store에 넣도록 수정 필요

## 체크리스트
- [ ] 새로고침 시에도 AccountObjId와 AccountTitle 을 store가 잘 가지고 있는지 (현재 기준 둘다 transaction store)

**Comment by yejineee** [comment]
이 부분 저랑 승환님이 작업했습니다! 내일 다시 알려드릴게요!

**Comment by pkiop** [comment]
앗 close하겠습니다
